Create ENV02_GP02_ProcedureForCommit.md
LouiseFuglsang/New-Yorker.dk pull request #56
Opened 2021-05-26 19:46 UTC by sasaje

Procedure for commit added.

2021-06-01 06:43 UTC, laan71 requested changes
Det ser fint ud på nær de 2 t ér

2021-06-01 06:43 UTC, laan71 commented on 09_Enviroment/ENV02_GP02_ProcedureForCommit.md
> +2.  Undervejs ved foretagelse af ændringer i indholdet af en branch, så skal man løbende committe sit arbejde til GitHub. Dette skal ske mindst én gang om dagen og helst én gang i timen. 
Der er et t for meget samt i linje 10

2021-06-02 12:02 UTC, ellamusen commented on 09_Enviroment/ENV02_GP02_ProcedureForCommit.md
> +    4.3 Knappen, som sender commitet klar til push *(Rød firkant 3)(se mere under procedure for push)*.
*comittet

2021-06-02 12:05 UTC, ellamusen commented on 09_Enviroment/ENV02_GP02_ProcedureForCommit.md
> +Beskrivelsen af commit-beskeden skal ligeledes være formuleret på engelsk også selvom at commitet indeholder artefakter eller analysedokumenter på dansk.
*comittet

2021-06-02 12:05 UTC, ellamusen commented on 09_Enviroment/ENV02_GP02_ProcedureForCommit.md
> +    4.3 Knappen, som sender commitet klar til push *(Rød firkant 3)(se mere under procedure for push)*.
*comittet

2021-06-09 19:17 UTC, ellamusen approved these changes
Super fint :)

2021-06-09 19:19 UTC, laan71 approved these changes
Det ser fint ud

2021-06-09 19:19 UTC, merged