Uc01 Fully Dressed
LouiseFuglsang/New-Yorker.dk pull request #67
Opened 2021-05-31 11:39 UTC by laan71

2021-06-02 09:06 UTC, sasaje commented on 02_Requirements/UseCases/REQ_UC03_UseCase01FullyDressed.md
> +Preconditions |	UC01, Væg er valgt, Navn og kontaktinfo er angivet |
UC01 er ikke en precondition for sig selv. 
Navn og kontaktinformation er heller ikke angivet på forhånd. 

Det eneste som er precondition er vel, at brugeren har åbnet produktkataloget. Da det er her use casen starter? :)

2021-06-02 09:07 UTC, sasaje commented on 02_Requirements/UseCases/REQ_UC03_UseCase01FullyDressed.md
> +Stakeholders and Interests | New-Yorker.dk |
Tilføj hvad deres interesser er. 
Brugerne skal også nævnes her og deres interesser.

2021-06-02 09:12 UTC, sasaje commented on 02_Requirements/UseCases/REQ_UC03_UseCase01FullyDressed.md
> +Succes Guarantee | Tilbudsbestillingen bliver afsendt korrekt |
Ændre "tilbudsbestillingen" til "tilbudsforespørgslen". 

Tilføj:
- "Ordren er gemt". 
- "Antal glas er udregnet korrekt ift. de af brugeren angivne mål".
- "Den samlede pris er opdateret efter det valgte".
- "De valgte produkter fra kurven er tilføjet til tilbudsforespørgslen korrekt". 
- "Tilbudsforespørgslen er godkendt af brugeren". 
- "Håndtering af persondatainformation er accepteret".
- "Tilbudsforespørgslen er afsendt korrekt".

2021-06-02 09:19 UTC, sasaje commented on 02_Requirements/UseCases/REQ_UC03_UseCase01FullyDressed.md
> +Main Succes Scenario |	1. Brugeren trykker på Bestil Tilbud <br> 2. Systemet præsenterer produktkatalog <br> 3. Brugeren vælger produkt(er) <br> 4. Brugeren lægger produkt(er) i kurv <br> 5. Systemet
Mellem nr. 3 og nr. 4 tilføjes: 
"Systemet opdaterer prisen i forhold til det valgte produkt".

I nr. 4. fjernes flertals benævnelsen, da man i main scenariet kun bestiller et produkt uden tilvalg. 

I nr 5.: ret enter til enten. 

Imellem 9. og 10. tilføjes:
    - "Systemet præsenterer forhandlerliste" 
    - "Brugeren vælger fortrukne forhandler fra forhandlerlisten"
    
    Erstat nr. 10 med:
"Systemet præsenterer en tilbudsforespørgselsoversigt med produkter, kontaktinformation, samlet pris, foretrukne forhandler."

Mellem 10 og 11. indsættes:
"Brugeren godkender indholdet af pkt. 10"

Til nr. 11.: "Brugeren godkender afsendelse af tilbudsforespørgsel".

Nr. 12 deles i to: 
"12. Systemet sender forespørgslen på mail" 
"13. Systemet præsenterer pop-up-besked om, at afsendelsen er sket korrekt".

2021-06-02 09:21 UTC, sasaje commented on 02_Requirements/UseCases/REQ_UC03_UseCase01FullyDressed.md
> +Extensions | 1. Brugeren vælger tilvalg frem for vægge <br> 2. Brugeren vælger "Shop videre" |
Skal uddybes til de forskellige alternativ flows (se evt. casual UC01).

2021-06-02 09:22 UTC, sasaje commented on 02_Requirements/UseCases/REQ_UC03_UseCase01FullyDressed.md
> +Technology and Data Variations List | NA |
Android telefon??

2021-06-02 09:23 UTC, sasaje requested changes
Se kommentarer til dokumentet :)

2021-06-10 15:08 UTC, LouiseFuglsang approved these changes

2021-06-10 15:09 UTC, merged