Created REQ06_OC01_OperationsContract.md
LouiseFuglsang/New-Yorker.dk pull request #94
Opened 2021-06-02 11:31 UTC by ellamusen

2021-06-02 18:51 UTC, sasaje commented on 02_Requirements/REQ06_OC01_OperationContract01.md
> +**Pre-conditions:** En bruger *br* eksisterer
De forskellige instanser af objekterne er her sat i kursiv. Enten tilføj det samme for de andre eller fjern kursiv her :)

2021-06-02 18:52 UTC, sasaje requested changes
Super fint, se kommentaren i dokumentet :)

2021-06-02 20:17 UTC, ellamusen commented on 02_Requirements/REQ06_OC01_OperationContract01.md
> +**Pre-conditions:** En bruger *br* eksisterer
Tak for feedback, jeg har opdateret filen :)

2021-06-03 07:08 UTC, sasaje approved these changes

2021-06-03 07:10 UTC, merged